# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG Project Name
tagline:          ''
description:      'A 2022 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://anikapotnis.github.io"
baseurl:          "/PolicyProject/"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/anikapotnis/PolicyProject/
